name: tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.platform == 'windows-latest'
        run: |
          WEB_ADDRESS=https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1
          curl -L $WEB_ADDRESS/msmpisetup.exe -o msmpisetup.exe || exit 1;
          curl -L $WEB_ADDRESS/msmpisdk.msi -o msmpisdk.msi || exit 1;
          ./msmpisetup.exe || exit 1;
          msiexec //i msmpisdk.msi || exit 1;
          export PATH=/c/Program\ Files/Microsoft\ MPI/bin:$PATH
      - if: matrix.platform == 'macos-latest'
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install open-mpi
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get install mpich libmpich-dev
      - run: pip --use-deprecated=legacy-resolver install -e .
      - run: python -We -c "import numba_mpi"
      - run: mpiexec -n 2 pytest -p no:unraisableexception -We
      # execute Python lines from README.md
      - run: awk < README.md 'BEGIN {cmt=1; swp=0;} {swp=(substr($0,1,3)=="```"); if (swp && !cmt) {cmt=1; swp=0} if (cmt) print("#" $0); else print $0; if (swp && cmt) {cmt=0; swp=0}}' | python
